services:
  - type: web
    name: cologne-ologist-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://starlit-pie-4e5b50.netlify.app
      - key: VITE_SUPABASE_URL
        value: https://tupjttqhkkjtlcvccjzj.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
